name: GCP Cloud Build

on:
  release:
    types: [published]

steps: 
        - name: Trigger Google Cloud Build
          args: ['cp', 'gs://Generalproject/index.html', 'gs://svproject/clonned_github_repo/']  
