name: Upload to GCS
description: Uploads a file to Google Cloud Storage
inputs:
  file-path:
    description: 'The path to the file to upload'
    required: true
  bucket:
    description: 'The name of the Google Cloud Storage bucket'
    required: true
runs:
  using: 'docker'
  image: 'google/cloud-sdk:alpine'
  entrypoint: 'bash'
  args: 
    - '-c'
    - 'gsutil cp ${{ inputs.index.html }} gs://${{ inputs.gs://shubhamprojectbucket/updatedvalues }}/'
