name: My Action
description: An example action that prints a message to the console
inputs:
  message:
    description: 'The message to print'
    required: true
outputs:
  time:
    description: 'The time the action was run'
    value: ${{ steps.timestamp.outputs.time }}
runs:
  using: 'bash'
  steps:
  - name: Print message
    run: |
      echo "${{ inputs.message }}"
  - name: Get timestamp
    id: timestamp
    run: |
      echo "::set-output name=time::$(date +%s)"
