name: connect-project
on:
  push:
    branches:
      - main
      - build
    paths:
     - 'index.html'
     - 'css/project-style.css/**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
