name: Upload to GCS

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
           contents: 'read'
           id-token: 'write'

    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0

    #  - name: Checkout my local action
      #  uses: actions/checkout@v2
       # with:
       #   repository: shubhamv0502/shubhamproject
       #   path: ./.github/actions/my-action

      - name: Set up GCP CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Run my local action
        uses: ./.github/actions/my-action

      - name: Upload file to GCS
        run: |
          gsutil cp index.html gs://shubhamprojectbucket/updatedvalues/
