name: connect-project
on:
  push:
    branches:
      - main
      - build
    paths:
     - 'index.html'
     - 'css.txt'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "updated"
