name: Upload to GCS

on:
  push:
    branches: main

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
           contents: 'read'
           id-token: 'write'

    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
                credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY}}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload repository to GCS
        run: |
           #gsutil cp shubhamproject/* gs://shubhamprojectbucket/updatedvalues/
           gsutil -m cp -r * gs://shubhamprojectbucket/updatedvalues/

